name: Ruby

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
    steps: 
      - uses: actions/checkout@v1
      - name: Setup ATests for Ruby
        run: |
          echo 'git $(git -v)'
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          exec $SHELL
          
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
          exec $SHELL
          
          rbenv install 2.6.5
          rbenv global 2.6.5
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build and Run Tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_MASTER_KEY: 123
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rails test
